// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOcl5d2ASgVVhOj7pYF6lUoWY9IPH-dcI',
    appId: '1:497504407261:web:fb68e0779bc34355fd5534',
    messagingSenderId: '497504407261',
    projectId: 'areteum-app',
    authDomain: 'areteum-app.firebaseapp.com',
    databaseURL: 'https://areteum-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'areteum-app.firebasestorage.app',
    measurementId: 'G-XH6RZ79TQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUcEnkBgATj9FXKgNz55HAX492REXLya8',
    appId: '1:497504407261:android:e9920239a88d2171fd5534',
    messagingSenderId: '497504407261',
    projectId: 'areteum-app',
    databaseURL: 'https://areteum-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'areteum-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYJ0v5g4Nise7zatkAaRvEKlTMdl8ywk',
    appId: '1:497504407261:ios:f38353523a94cb4bfd5534',
    messagingSenderId: '497504407261',
    projectId: 'areteum-app',
    databaseURL: 'https://areteum-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'areteum-app.firebasestorage.app',
    iosBundleId: 'com.example.areteumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaYJ0v5g4Nise7zatkAaRvEKlTMdl8ywk',
    appId: '1:497504407261:ios:f38353523a94cb4bfd5534',
    messagingSenderId: '497504407261',
    projectId: 'areteum-app',
    databaseURL: 'https://areteum-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'areteum-app.firebasestorage.app',
    iosBundleId: 'com.example.areteumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOcl5d2ASgVVhOj7pYF6lUoWY9IPH-dcI',
    appId: '1:497504407261:web:a735b6547a41b0bbfd5534',
    messagingSenderId: '497504407261',
    projectId: 'areteum-app',
    authDomain: 'areteum-app.firebaseapp.com',
    databaseURL: 'https://areteum-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'areteum-app.firebasestorage.app',
    measurementId: 'G-7LP5X9MZFY',
  );

}